### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by miraito** [ucan-lab/laravel-dacapo#79]
`--refresh` オプションを使用した場合 yml の定義が変更される為変更内容次第で `Migration not found: 1970_01_01_090000_create_my_table` のようなエラーが出る事がります。

`migrations` テーブルを truncate してから migration をする方が良さそうです。

**Comment by ucan-lab** [comment]
`--refresh` はロールバックの動作確認をしたい時に行います。
`schema.yml` を変更して `--refresh` するとオートローダが存在しないファイルを記憶してしまってるので、`Migration not found` が発生します。

`--fresh` オプションを使用すると drop table & create table を行ってくれます。

```
$ php artisan dacapo:generate --fresh
```

`schema.yml` を変更しないかつ、ロールバックが動作するか確認したい場合のみ `--refresh` オプションを使用してください。
